import { z } from "zod";

export const personalDataSchema = z.object({
  ci: z.string(),
  status: z.string(),
  surnames: z.string(),
  campus: z.string(),
  names: z.string(),
  career: z.string(),
  coursedUC: z.number(),
  academicIndex: z.number(),
  approvedUC: z.number(),
  level: z.number(),
  record: z.string(),
  academicEmail: z.string(),
  email: z.string(),
  alternativEmail: z.string().nullish(),
  phoneNumber: z.string(),
  alternativePhoneNumber: z.string().nullish(),
  birthdate: z.string(),
  birthplace: z.string(),
  genre: z.string(),
  state: z.string(),
  country: z.string(),
  maritalStatus: z.string(),
  address: z.string(),
});

export const academicDataSchema = z.object({
  technologicalDegree: z.number().nullish(),
  professionalDegree: z.number().nullish(),
  firstSemester: z.string(),
  lastSemester: z.string(),
  pensum: z.number(),
  level: z.number(),
  coursedUC: z.number(),
  approvedUC: z.number(),
  technologicalUC: z.number(),
  profesionalUC: z.number(),
  readmissions: z.number().nullish(),
  careerChanges: z.number().nullish(),
  repeatsRegimen: z.number().nullish(),
  withdrawals: z.number().nullish(),
  courseIndex: z.number(),
  academicIndex: z.number(),
  projectIndex: z.number(),
  technologicalIndex: z.number(),
  lastIndex: z.number(),
  registrationDate: z.string(),
  registeredBy: z.string(),
  registrationOrigin: z.string(),
  formNumber: z.string().nullish(),
  campus: z.string(),
  career: z.string(),
});
